server:
  port: 8887

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/library?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
